SiDECLARAv003_2_3_lts_instalacion/SiDECLARAv001_240221/proyecto/declaraciones/declaraciones/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path
from django.conf.urls import include, url
from declaracion import urls
from sitio import urls
from api import urls
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', include('sitio.urls')),
    path('admin/', admin.site.urls),
    path('declaracion/', include('declaracion.urls')),
    path('api/', include('api.urls')),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name ='reset_password'),  
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name ='password_reset_done'),  
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name ='password_reset_confirm'),  
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name ='password_reset_complete')
]

# front-edit
#urlpatterns += [
#    url(r'^front-edit/', include('front.urls')),
#]

admin.site.site_header = 'Administración de Declaraciones'
admin.site.site_title = 'Administración de Declaraciones'
admin.site.index_title =  'Bienvenido a la administración del sistema'

SiDECLARAv003_2_3_lts_instalacion/SiDECLARAv001_240221/proyecto/declaraciones/urls.py
from django.conf.urls import url

from . import views


app_name = "oauth2_provider"


base_urlpatterns = [
    url(r"^authorize/$", views.AuthorizationView.as_view(), name="authorize"),
    url(r"^token/oauth/$", views.TokenView.as_view(), name="token"),
    url(r"^revoke_token/$", views.RevokeTokenView.as_view(), name="revoke-token"),
    url(r"^introspect/$", views.IntrospectTokenView.as_view(), name="introspect"),
]


management_urlpatterns = [
    # Application management views
    url(r"^applications/$", views.ApplicationList.as_view(), name="list"),
    url(r"^applications/register/$", views.ApplicationRegistration.as_view(), name="register"),
    url(r"^applications/(?P<pk>[\w-]+)/$", views.ApplicationDetail.as_view(), name="detail"),
    url(r"^applications/(?P<pk>[\w-]+)/delete/$", views.ApplicationDelete.as_view(), name="delete"),
    url(r"^applications/(?P<pk>[\w-]+)/update/$", views.ApplicationUpdate.as_view(), name="update"),
    # Token management views
    url(r"^authorized_tokens/$", views.AuthorizedTokensListView.as_view(), name="authorized-token-list"),
    url(r"^authorized_tokens/(?P<pk>[\w-]+)/delete/$", views.AuthorizedTokenDeleteView.as_view(),
        name="authorized-token-delete"),
]


urlpatterns = base_urlpatterns + management_urlpatterns

SiDECLARAv003_2_3_lts_instalacion/SiDECLARAv001_240221/proyecto/declaraciones/declaracion/models/informacion_personal.py
import uuid
import os
from django.contrib.auth.models import User
from django.db import models
from django.db.models import CASCADE
from django.urls import reverse_lazy
from smart_selects.db_fields import ChainedForeignKey

from .catalogos import (CatPaises, CatEstadosCiviles,
                        CatTiposDeclaracion, CatRegimenesMatrimoniales,
                        CatGradosAcademicos, CatEstatusEstudios,
                        CatDocumentosObtenidos, CatEntesPublicos,
                        CatOrdenesGobierno,CatSectoresIndustria,
                        CatFuncionesPrincipales, CatAmbitosLaborales,
                        CatTiposRelacionesPersonales, CatPoderes,
                        CatTipoPersona, CatEntidadesFederativas, CatTipoVia,
                        CatMunicipios, CatMonedas,CatTiposOperaciones,CatEstatusDeclaracion,CatPuestos,CatAreas)
from django.db.models.signals import post_delete
from django.dispatch import receiver

#Se agrego variable global para los campos de modelos que lo necesiten ya que la informaciòn es la misma
TIPO_OPERACION = [
    ('AGREGAR', 'Agregar'),
    ('MODIFICAR', 'Modificar'),
    ('SIN_CAMBIO', 'Sin cambio'),
    ('BAJA', 'Baja')
]


class InfoPersonalFija(models.Model):
    """
    En este modelo se guarda la información personal del declarante
    """
    nombres = models.CharField(max_length=255, blank=True)
    apellido1 = models.CharField(max_length=255, blank=True, verbose_name="Apellido Paterno")
    apellido2 = models.CharField(max_length=255, blank=True, verbose_name="Apellido Materno")
    curp = models.CharField(max_length=255, blank=True)
    puesto = models.CharField(max_length=255, blank=True, null=True)
    cat_puestos = models.ForeignKey(CatPuestos, on_delete=models.DO_NOTHING, blank=True, null=True,verbose_name="Puesto") # AGREGADO 10/03/21 GG
    rfc = models.CharField(max_length=255, blank=True)
    telefono = models.CharField(max_length=14, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True, null=True)
    cat_ente_publico = models.ForeignKey(CatEntesPublicos, on_delete=models.DO_NOTHING, blank=True, null=True)
    cat_entidades_federativas = models.ForeignKey(CatEntidadesFederativas, on_delete=models.DO_NOTHING, null=True, blank=True)
    nombre_ente_publico = models.CharField(max_length=300, null=True, blank=True)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    cat_pais = models.ForeignKey(CatPaises, on_delete=models.DO_NOTHING, null=True, blank=True)
    otro_ente = models.CharField(max_length=255, blank=True, null=True)
    fecha_inicio = models.DateField(blank=True, null=True)
    sended = models.BooleanField(blank=True, null=True, default=False)

    def nombre_completo(self):
        return u"{} {} {}".format(self.nombres, self.apellido1,self.apellido2)



class Declaraciones(models.Model):
    """
    Modelo que guarda información de la declaración
    """
    folio = models.UUIDField(primary_key=False, default=uuid.uuid4, editable=False)
    fecha_recepcion = models.DateTimeField(blank=True, null=True)
    fecha_declaracion = models.DateField(null=True, auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    cat_tipos_declaracion = models.ForeignKey(CatTiposDeclaracion, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_estatus = models.ForeignKey(CatEstatusDeclaracion, on_delete=models.DO_NOTHING, default=1)
    avance = models.IntegerField(blank=True,default=0)
    info_personal_fija = models.ForeignKey(InfoPersonalFija, on_delete=models.DO_NOTHING)
    extemporanea = models.BooleanField(blank=True, null=True, default=0)
    datos_publicos = models.BooleanField(blank=True, null=True, default=0)


class Domicilios(models.Model):
    """
    Modelo que guarda información de los domicilios
    ---------
    Debido a que existen multiples personas relacionadas que se crearán en la declaración 
    muchas contarán con direcciones propias(ej. Dependientes economicos)
    """
    cp = models.CharField(max_length=255, blank=True)
    colonia = models.CharField(max_length=255, blank=True)
    nombre_via = models.CharField(max_length=255, blank=True)
    num_exterior = models.CharField(max_length=255, blank=True)
    num_interior = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    cat_entidades_federativas = models.ForeignKey(CatEntidadesFederativas, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_pais = models.ForeignKey(CatPaises, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_tipo_via = models.ForeignKey(CatTipoVia, on_delete=models.DO_NOTHING, null=True, blank=True)
    municipio = models.ForeignKey(CatMunicipios, on_delete=models.DO_NOTHING,blank=True, null=True)
    ciudadLocalidad = models.CharField(max_length=100, blank=True, null=True)
    estadoProvincia = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        ordering=('pk',)

    def __str__(self):
        try: 
            return self.nombre_via + self.num_exterior + self.num_interior + self.colonia + self.cp  
        except:
            return "Domicilio"


class Observaciones(models.Model):
    """
    Modelo que guarda las observaciones por secciones
    """
    observacion = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.observacion


class InfoPersonalVar(models.Model):
    """
    Modelo que guarda información de multiples personas relacionadas a una declaración del declarante
    ---------
    Uso principal: Guarda información de
                                        -Pareja
                                        -Dependientes economicos
                                        -Empresa
                                        -Cliente
                                        -Etc, Más en el catálogo tipoPersona
    """
    TIPO_DECLARANTE = 1
    TIPO_DEPENDIENTE = 2
    TIPO_EMPRESA = 3
    TIPO_SOCIO = 4
    TIPO_CLIENTE = 5
    TIPO_SOCIEDAD = 6
    TIPO_INSTITUCION = 7
    TIPO_FIDEICOMISARIO = 8
    TIPO_FIDEICOMITENTE = 9
    TIPO_FIDUCIARIO = 10
    TIPO_COPROPIETARIO = 12
    TIPO_PROPIETARIO_ANTERIOR = 13
    TIPO_PRESTATARIO = 14
    es_fisica = models.BooleanField(blank=True, null=True, default=None)
    razon_social = models.CharField(max_length=255, blank=True, null=True)
    nombres = models.CharField(max_length=255, blank=True)
    apellido1 = models.CharField(max_length=255, blank=True)
    apellido2 = models.CharField(max_length=255, blank=True)
    curp = models.CharField(max_length=255, blank=True)
    rfc = models.CharField(max_length=255, blank=True)
    homoclave = models.CharField(max_length=3, blank=True, null=True)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    num_id_identificacion = models.CharField(max_length=255, blank=True)
    email_personal = models.CharField(max_length=255, blank=True)
    tel_particular = models.CharField(max_length=255, blank=True)
    tel_movil = models.CharField(max_length=255, blank=True)
    cat_entidades_federativas = models.ForeignKey(CatEntidadesFederativas, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_estados_civiles = models.ForeignKey(CatEstadosCiviles, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_pais = models.ForeignKey(CatPaises, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_regimenes_matrimoniales = models.ForeignKey(CatRegimenesMatrimoniales, on_delete=models.DO_NOTHING, null=True, blank=True)
    declaraciones = models.ForeignKey(Declaraciones, on_delete=models.DO_NOTHING)
    domicilios = models.ForeignKey(Domicilios, on_delete=models.DO_NOTHING, blank=True, null=True)
    observaciones = models.ForeignKey(Observaciones, on_delete=models.DO_NOTHING, blank=True, null=True)
    cat_tipo_persona = models.ForeignKey(CatTipoPersona, on_delete=models.DO_NOTHING, blank=True, null=True)
    cat_sectores_industria = models.ForeignKey(CatSectoresIndustria, on_delete=models.DO_NOTHING, blank=True, null=True)
    otro_sector = models.CharField(max_length=255, blank=True, null=True)
    otro_estado_civil = models.CharField(max_length=255, blank=True, null=True)
    actividad_economica = models.CharField(max_length=255, blank=True, null=True)
    ocupacion_girocomercial = models.CharField(max_length=255, blank=True, null=True)
    nombre_negocio = models.CharField(max_length=255, blank=True, null=True)
    rfc_negocio = models.CharField(max_length=50, blank=True, null=True) #/AGREGADO
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    nacionalidades = models.ManyToManyField(CatPaises, through='Nacionalidades', related_name="info_personal_var_nacionalidaes", blank=True)
    activos_bienes = models.ManyToManyField(
        'ActivosBienes',
        through='BienesPersonas',
        through_fields=('info_personal_var', 'activos_bienes'),
        related_name="info_personal_var_activos_bienes")


    class Meta:
        ordering=('pk',)

    def __str__(self):
        return self.rfc

    def nombre_completo(self):
        if self.es_fisica:
            return ("%s %s %s")%(self.nombres ,self.apellido1,self.apellido2)
        else:
            return self.razon_social

    def domicilio(self):
        return [self.domicilios]

    def observacion(self):
        return [self.observaciones]

    def nacionalidad(self):
        try:
            return self.nacionalidades.all()
        except:
            return None

    def tipo(self):
        return self.cat_tipo_persona_id

    def sectores_industrias(self):
        try:

SiDECLARAv003_2_3_lts_instalacion/SiDECLARAv001_240221/proyecto/declaraciones/declaracion/forms/confirmacion.py
from django import forms
from django.core.validators import FileExtensionValidator


class ConfirmacionForm(forms.Form):
   datos_publicos = forms.TypedChoiceField(
                    coerce=lambda x: x == 'True',
                    choices=((False, 'False'), (True, 'True')),
                    widget=forms.RadioSelect,
                    required=False
                   )

SiDECLARAv003_2_3_lts_instalacion/SiDECLARAv001_240221/proyecto/declaraciones/declaracion/views/api.py
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.views import View

from declaracion.models import Declaraciones
from datetime import datetime
from django.core.paginator import Paginator
from django.shortcuts import render

class RegistrosView(View):
    template_name = "reportes/publico.json.html"


    def get(self, request, *args, **kwargs):
        api_key = request.GET.get('api_key')
        sort = request.GET.get('sort')
        page = request.GET.get('page')
        page_size = request.GET.get('page_size')
        nombres = request.GET.get('nombres')
        apellido1 = request.GET.get('apellido1')
        apellido2 = request.GET.get('apellido2')
        rfc = request.GET.get('rfc')
        curp = request.GET.get('rfc')

        id = request.GET.get('id')
        actualizacion = request.GET.get('actualizacion')
        rfc_solicitante = request.GET.get('rfc_solicitante')
        filter = False


        declaraciones = Declaraciones.objects
        if id and id != "":
            declaraciones = declaraciones.filter(folio=id)
            filter=True
        if rfc and rfc != "":
            declaraciones = declaraciones.filter(info_personal_fija__rfc=rfc.upper())
            filter=True
        if curp and curp != "":
            declaraciones = declaraciones.filter(info_personal_fija__curp=curp.upper())
            filter = True
        if nombres and nombres != "":
            declaraciones = declaraciones.filter(info_personal_fija__nombres__contains=nombres.upper())
            filter = True
        if apellido1 and apellido1 != "":
            declaraciones = declaraciones.filter(info_personal_fija__apellido1__contains=apellido1.upper())
            filter = True
        if apellido2 and apellido2 != "":
            declaraciones = declaraciones.filter(info_personal_fija__apellido2__contains=apellido2.upper())
            filter = True
        if sort and sort.upper() == "ASC":
            declaraciones = declaraciones.order_by('fecha_declaracion')
            filter = True
        elif sort and sort.upper() == "DESC":
            declaraciones = declaraciones.order_by('-fecha_declaracion')
            filter = True
        if actualizacion and actualizacion != "":
            actualizacion = datetime.strptime(actualizacion, "%Y-%m-%d")
            declaraciones = declaraciones.filter(fecha_declaracion__gte=actualizacion)
            filter = True
        if not filter:
            declaraciones=declaraciones.all()

        if page_size and page:
            paginator = Paginator(declaraciones, int(page_size))
            declaraciones = paginator.get_page(int(page))
        response = render_to_string(self.template_name, {
            'declaraciones': declaraciones
        })
        return HttpResponse(content = response,content_type="application/json")

SiDECLARAv003_2_3_lts_instalacion/SiDECLARAv001_240221/proyecto/declaraciones/templates/declaracion/admin/frm_domicilio.html
<h6 class="text-success-lighter p_opciones mb-0">Domicilio</h6>
<dl class="p_opciones">
  <dt>Código postal</dt>
  <dd class="text-black_opciones">{{ domicilio.cp|default_if_none:"" }}</dd>
</dl>
<dl class="p_opciones">
  <dt>País</dt>
  <dd class="text-black_opciones">{{ domicilio.cat_pais|default_if_none:"" }}</dd>
</dl>
<dl class="p_opciones">
  <dt>Entidad federativa</dt>
  <dd class="text-black_opciones">{{ domicilio.cat_entidades_federativas|default_if_none:"" }}</dd>
</dl>
<dl class="p_opciones">
  <dt>Municipio</dt>
  <dd class="text-black_opciones">{{ domicilio.municipio|default_if_none:"" }}</dd>
</dl>
<dl class="p_opciones">
  <dt>Colonia</dt>
  <dd class="text-black_opciones">{{ domicilio.colonia|default_if_none:"" }}</dd>
</dl>
<dl class="p_opciones">
  <dt>Tipo de vía</dt>
  <dd class="text-black_opciones">{{ domicilio.cat_tipo_via|default_if_none:"" }}</dd>
</dl>
<dl class="p_opciones">
  <dt>Nombre de vía</dt>
  <dd class="text-black_opciones">{{ domicilio.nombre_via|default_if_none:"" }}</dd>
</dl>
<dl class="p_opciones">
  <dt>Número exterior</dt>
  <dd class="text-black_opciones">{{ domicilio.num_exterior|default_if_none:"" }}</dd>
</dl>
<dl class="p_opciones">
  <dt>Número interior</dt>
  <dd class="text-black_opciones">{{ domicilio.num_interior|default_if_none:"" }}</dd>
</dl>

SiDECLARAv003_2_3_lts_instalacion/SiDECLARAv001_240221/proyecto/declaraciones/templates/declaracion/admin/registro_usuario_declarante.html
{% extends "layout/base.html" %}
{% load static %}
{% block header_title %}Crear nuevo declarante{% endblock %}
{% load bootstrap4 %}
{% block content %}
<section class="container-fluid container-offset-x my-md-7 py-7">
    <div class="row row-md">
        <div class="col-sm-12 col-md-8">
            {% if not editar %}
            <h1 class="text-gray text-xl font-weight-medium text-uppercase mt-5 line-height-md title-mobile text-mobile">
               <span class="text-primary-light font-weight-semibold">Crear declarante</span>
             </h1>
                {% else %}
            <h1 class="text-gray text-xl font-weight-medium text-uppercase mt-5 line-height-md title-mobile text-mobile">
               <span class="text-primary-light font-weight-semibold">Editar declarante</span>
            </h1>
            {% endif %}
        </div>
        <div class="col-sm-12 col-md-4 mt-4" style="text-align: right;">
            <a href="{% url 'declaracion:busqueda-declarantes' %}" class="btn btn-success text-uppercase font-weight-semibold mx-3">
               <img src="{% static 'src/img/regresar.png' %}"> 
               Regresar
            </a>
        </div>
    </div>
    <p class="text-gray-darker font-weight-light">Todos lo campos son obligatorios</p>
    {% if not editar %}
        <form action="{% if is_staff %}{% url 'declaracion:nuevo-usuario-declarante' %}{% else %}{% url 'declaracion:nuevo' %}{% endif %}" method="post" novalidate>
    {% else %}
        <form {% if not preregistro %} id="form_usuarioDeclarante" {% endif %}  action="{% if is_staff %}{% url 'declaracion:editar-usuario-declarante' editar tipo_registro %}{% else %}{% url 'declaracion:nuevo' %}{% endif %}" method="post" novalidate>
    {% endif %}
    {% csrf_token %}
        <div class="row" style="margin: 0 10em;">
            <div class="col-lg-12">
                <div class="row">
                    {% if editar and tipo_registro == 'registrado' or tipo_registro == 'registrado_sindec' or tipo_registro == 'todos'  %}
                        <div class="col-md-6">
                            {% bootstrap_field form.estatus placeholder="Estatus"  %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_field form.fecha_inicio placeholder="Fecha de ingreso"  %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_field form.cat_areas addon_before='<span class="" >Área</span>' %}
                        </div>
                        <div class="col-md-6">
                            <div class="input-group mb-3">             
                              <div class="input-group-prepend"><label class="input-group-text" >Puesto</label></div>
                              <!--Selectpiker para la busqueda puestos add Jeremias -  10/07/2023-->
                              <select id="id_cat_puestos" name="cat_puestos" class="form-control selectpicker" data-live-search="true">              
                              </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_field form.nombres placeholder="Nombre(s)" %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_field form.apellido1 placeholder="Primer Apellido" %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_field form.apellido2 placeholder="Segundo Apellido" %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_field form.rfc placeholder="RFC con homoclave" field_class='valida_rfc'  %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_field form.email placeholder="Correo electrónico" field_class='valida_email'  %}
                        </div>
                    {% else %}
                        <div class="col-md-6">
                            {% bootstrap_field form.first_name placeholder="Nombre(s)" %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_field form.last_name placeholder="Primer apellido" %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_field form.username placeholder="RFC con homoclave" field_class='valida_rfc'  %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_field form.email placeholder="Correo electrónico" field_class='valida_email'  %}
                        </div>
                        <!---
                        Si el usuario no tiene registro en info fija y desea activarlo desde aquí se va a generar un error
                        <div class="col-md-12">
                            {% bootstrap_field form.is_active %}
                        </div>-->

                    {% endif %}
                    <div class="col-12 text-right">
                        <button type="submit" class="btn bgCVerdeSeco btn-success btn-block btn-lg font-weight-semibold">
                            {% if editar %}
                                Guardar cambios 
                            {% else %}
                                Crear declarante
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</section>
{% endblock %}

SiDECLARAv003_2_3_lts_instalacion/SiDECLARAv001_240221/proyecto/declaraciones/templates/declaracion/admin/registro_usuario_oic.html
{% extends "layout/base.html" %}
{% load static %}
{% block header_title %}Crear nuevo usuario{% endblock %}
{% load bootstrap4 %}

{% block content %}
<section class="container-fluid container-offset-x my-md-7 py-7">

  <div class="row row-md ">
     <div class="col-sm-12 col-md-8">
         {% if not editar %}
        <h1 class="text-gray text-xl font-weight-medium text-uppercase mt-5 line-height-md title-mobile text-mobile"><span class="text-primary-light font-weight-semibold">Crear usuario</span> </h1>
             {% else %}
        <h1 class="text-gray text-xl font-weight-medium text-uppercase mt-5 line-height-md title-mobile text-mobile"><span class="text-primary-light font-weight-semibold">Editar usuario</span> </h1>

         {% endif %}
     </div>
     <div class="col-sm-12 col-md-4 mt-4" style="text-align: right;">
        <a href="{% url 'declaracion:busqueda-usuarios' %}" class="btn btn-success text-uppercase font-weight-semibold mx-3">
          <img src="{% static 'src/img/regresar.png' %}">
          Regresar
        </a>
     </div>
  </div>
  <p class="text-gray-darker font-weight-light">Todos lo campos son obligatorios</p>
{% if not editar %}
  <form id="form_usuarioOIC" action="{% if is_staff %}{% url 'declaracion:nuevo-usuario' %}{% else %}{% url 'declaracion:nuevo' %}{% endif %}" method="post" novalidate>
    {% else %}
  <form id="form_usuarioOIC" action="{% if is_staff %}{% url 'declaracion:editar-usuario' form.id.value %}{% else %}{% url 'declaracion:nuevo' %}{% endif %}" method="post" novalidate>
  {% endif %}
    {% csrf_token %}
    <div class="row" style="margin: 0 8em;">
      <div class="col-lg-12">
        <div class="row">
          <div class="col-md-6">
            {% bootstrap_field form.nombres placeholder="Nombre(S)" field_class="solo_letras"  %}
          </div>
          <div class="col-md-6">
              {% bootstrap_field form.apellido1 placeholder="Primer Apellido" field_class="solo_letras"  %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.apellido2 placeholder="Segundo Apellido" field_class="solo_letras" required=False  %}
          </div>
          {% if es_oic %}
          <div class="col-md-6">
            {% bootstrap_field form.usuario placeholder="Usuario"   %}
          </div>
          {%else%}
          <div class="col-md-6">
            {% bootstrap_field form.rfc placeholder="RFC" field_class='valida_rfc'  %}
          </div>
          {%endif%}
          <div class="col-md-12">
            {% bootstrap_field form.nombre_ente_publico placeholder="Ente público"  %}
          </div>
          
          <div class="col-md-6">
            {% bootstrap_field form.cat_areas placeholder="Area" field_class="solo_letras"  addon_before='<span class="" >Área</span>' %}
          </div>
          
          <div class="col-md-6">
            <div class="input-group mb-3">             
              <div class="input-group-prepend"><label class="input-group-text" >Puesto</label></div>
              <!--Selectpiker para la busqueda puestos add Jeremias -  10/07/2023-->
              <select id="id_cat_puestos" name="cat_puestos" class="form-control selectpicker" data-live-search="true">              
              </select>
            </div>
          </div> 

          <div class="col-md-6">
            {% bootstrap_field form.telefono placeholder="Teléfono" field_class="valida_telefono"  %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.email placeholder="Correo electrónico" field_class='valida_email'  %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.estatus placeholder="Estatus"  %}
          </div>
          <div class="col-md-6">
            {% bootstrap_field form.rol placeholder="Rol" %}
          </div>
            {% if editar %}
            {{ form.id }}
            {% endif %}

          <div class="col-12 text-right">
            <button type="submit" class="btn bgCVerdeSeco btn-success btn-block btn-lg font-weight-semibold">{% if editar %}Guardar cambios {% else %}Crear usuario{% endif %}</button>
            {% if editar %}{% else %}<p class="text-center text-danger">Se enviará un correo al usuario que se está registrando con las instrucciones para entrar al sistema una vez terminado</p>{% endif %}
          </div>
        </div>
      </div>
    </div>
  </form>
</section>
{% endblock %}